package dev.musicplayer.theme;
import java.nio.file.Path;import java.util.*;
public final class Theme{
 public String id="default",name="Midnight Glass";public int version=4;public Background background=new Background();public String accent="#FFFFFF",secondary="#A8ABB4",text="#FFFFFF";public int panelRadius=18;public boolean shadow=true;public Visualizer visualizer=new Visualizer();public Cover cover=new Cover();public Notification notification=new Notification();public Island island=new Island();public Font font=new Font();public List<Layer> layers=defaultLayers();public transient Path root;
 public static List<Layer> defaultLayers(){return new ArrayList<>(List.of(new Layer("cover","Cover",10,10,104,104),new Layer("title","Track title",130,18,260,20),new Layer("artist","Artist",130,42,260,18),new Layer("progress","Progress",130,72,340,6),new Layer("controls","Controls",130,84,210,28),new Layer("volume","Volume",370,84,110,28),new Layer("visualizer","Visualizer",490,30,115,65)));}
 public static final class Background{public String type="color",color="#101116",color2="#171A25",gradient="none",image="";public double opacity=.94,dynamicStrength=.35,imageOpacity=1,blur=0,animationSpeed=.25,gradientAngle=0;public boolean dynamicCover=false;}
 public static final class Visualizer{public boolean enabled=true;public String type="bars";public double sensitivity=1,smoothing=.75,opacity=.65;public int barCount=32;public boolean mirror=false;public int smoothingFrames=3;public double particleSpeed=1,particleDensity=.7,waveThickness=2;public boolean particles=true;public double radius=.28,thickness=1.0,rotationSpeed=1.0;public boolean glow=false,filled=true;public String colorMode="accent";public double bass=.33,mid=.66,treble=1.0;public double decay=.18,peakHold=.35;public boolean peak=true;public int rings=3;public double ringGap=.22;}
 public static final class Cover{public String mode="static";public int radius=14;public boolean rotate=false,pulse=false;public double scale=1,rotationSpeed=35,overlayOpacity=0,borderWidth=0;public String borderColor="#FFFFFF",overlayColor="#000000";public boolean showDisc=true,showCenter=true,shadow=true;public double pulseAmount=.025;public double reactiveAmount=.12,reactiveSensitivity=1;public boolean reactiveBass=true,reflect=false;public double floatAmplitude=8,floatSpeed=2.1;public int discRings=10;public double discTilt=0;public String mask="none";}
 public static final class Notification{public boolean enabled=true;public String position="top_center",animation="slide";public long durationMs=2600;public boolean showCover=true,showControls=true;public int width=320,height=64;}
 public static final class Island{public boolean enabled=true;public String position="top_center",mode="compact",animation="slide";public int width=320,height=34;public double opacity=.92;public boolean showArtist=true,showCover=true,showProgress=true,showControls=false,showVisualizer=false;public double animationSpeed=.9,cornerRadius=18;public int visualizerWidth=72;}
 public static final class Font{public String family="minecraft",file="";}
 public static final class Layer{public String id,label,group="",kind="auto",text="",blend="normal",color="#FFFFFF",color2="#FFFFFF",gradient="none",image="",animation="none",mask="none",easing="smooth";public double x,y,width,height,rotation=0,opacity=1;public double animationSpeed=1,animationAmplitude=1,animationPhase=0;public boolean animateOpacity=false,animateScale=false;public boolean visible=true,locked=false,shadow=false,glow=false,clip=false;public String reactive="none";public double reactiveAmount=0,reactiveSensitivity=1,reactiveBand=.15;public int fontSize=16,radius=10,maskRadius=16;public List<Keyframe> keyframes=new ArrayList<>();public Layer(){}public Layer(String id,String label,double x,double y,double w,double h){this.id=id;this.label=label;this.x=x;this.y=y;this.width=w;this.height=h;} public void addKeyframe(double time){keyframes.add(new Keyframe(time,x,y,width,height,rotation,opacity,1));keyframes.sort(Comparator.comparingDouble(k->k.time));} } public static final class Keyframe{public double time,x,y,width,height,rotation,opacity,scale=1;public Keyframe(){}public Keyframe(double time,double x,double y,double width,double height,double rotation,double opacity,double scale){this.time=time;this.x=x;this.y=y;this.width=width;this.height=height;this.rotation=rotation;this.opacity=opacity;this.scale=scale;}}
}
